package animation;

public enum AnimationState {

    // BASE STATE
    BASE,

    // ITEMS
    CARRY_PLATE,
    CARRY_PLATE_DIRTY,
    CARRY_PAN,

    // INGREDIENTS ONLY
    CARRY_CORNEDBEEF,
    CARRY_EGG,
    CARRY_ONION,
    CARRY_RAW_RICE,
    CARRY_SPAM,
    CARRY_TAPA,

    // DRINKS
    CARRY_COKE,
    CARRY_WATER,


    // DISHES
    CARRY_TAPSILOG,
    CARRY_SPAMSILOG,
    CARRY_CORNSILOG,

    // ONE INGREDIENT
    CARRY_EGG_PLATE,
    CARRY_RICE_PLATE,
    CARRY_TAPA_PLATE,
    CARRY_CB_PLATE,
    CARRY_SPAM_PLATE,

    // TAPSI INSTANCE
    CARRY_TAPSI_PLATE,
    CARRY_TAPLOG_PLATE,

    // SPAMSI INSTANCE
    CARRY_SPAMSI_PLATE,
    CARRY_SPAMLOG_PLATE,


    // CORNSI INSTANCE
    CARRY_CORNSI_PLATE, //CORNSILOG WITHOUT EGG
    CARRY_CORNLOG_PLATE; //CORNSILOG WITHOUT RICE


}
