package animation;

public enum AnimationState {

    // BASE STATE
    BASE,

    // ITEMS
    CARRY_PLATE,
    CARRY_DIRTYPLATE,

    // INGREDIENTS ONLY
    CARRY_CORNEDBEEF,
    CARRY_EGG,
    CARRY_ONION,
    CARRY_RAWRICE,
    CARRY_SPAM,
    CARRY_TAPA,

    // DRINKS
    CARRY_COKE,
    CARRY_WATER,

    // DISHES
    CARRY_TAPSILOGFINAL,
    CARRY_SPAMSILOGFINAL,
    CARRY_CORNSILOGFINAL,

    // ONE INGREDIENT
    CARRY_COOKEDEGGONLY,
    CARRY_ONIONONLY,
    CARRY_COOKEDRICEONLY,
    CARRY_COOKEDTAPAONLY,
    CARRY_COOKEDCBEEFONLY,
    CARRY_COOKEDSPAMONLY,

    // TAPSI INSTANCE
    CARRY_TAPSILOGNOEGG,
    CARRY_TAPSILOGNORICE,

    // SPAMSI INSTANCE
    CARRY_SPAMSILOGNOEGG,
    CARRY_SPAMSILOGNORICE,


    // CORNSI INSTANCE
    CARRY_CORNSILOGNOEGG, //CORNSILOG WITHOUT EGG
    CARRY_CORNSILOGNORICE, //CORNSILOG WITHOUT RICE

    // PAN INSTANCES
    CARRY_PAN,
    CARRY_PAN_BURNT,
    CARRY_PAN_CBEEF,
    CARRY_PAN_EGG,
    CARRY_PAN_ONION,
    CARRY_PAN_CBEEFEGG,
    CARRY_PAN_SPAM,
    CARRY_PAN_TAPA;

}
